#!/usr/bin/env ruby -w
$LOAD_PATH.unshift File.join(File.dirname(__FILE__), *%w( .. lib ))

require 'zooqle_search'
require 'fileutils'
require 'highline'
require 'optparse'

options = {
  path: './'
}

optparse = OptionParser.new do |opts|
  opts.banner = 'Usage: zooqle_search [options] <search>'

  opts.on('-y', '--auto-download', 'Download first result without confirmation') do
    options[:auto] = true
  end

  opts.on('-m', '--magnet', 'Print magnet link and exit') do
    options[:magnet] = true
  end

  opts.on('-p PATH', '--path PATH', 'Path to save the file') do |p|
    options[:path] = p
  end

  opts.on('-v', '--version', 'Print version and exit') do
    puts "zooqle_search v#{ZooqleSearch::VERSION}"
    exit
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end.parse!

# Join arguments to create the search term
options[:search] = optparse.join(' ')

# main program
begin
  cli = HighLine.new
  HighLine.colorize_strings # Monkey patch String for cli colors

  # Valid search?
  if options[:search].empty?
    cli.say 'Please type a search'.red
    exit
  end

  # Search subtitle
  search = ZooqleSearch::Search.new(options[:search])

  # Results found?
  unless search.results_found?
    cli.say 'No results found'.red
    exit
  end

  # Choose
  if options[:auto]
    torrent = search.links.first
  else
    cli.say "Search results for #{options[:search]}:"
    torrent = cli.choose(*search.links) do |menu|
      menu.default = '1'
      menu.select_by = :index
    end
  end

  # Download torrent or print magnet link
  if options[:magnet]
    cli.say torrent.magnet
  else
    torrent_file = torrent.download(options[:path])
    cli.say "#{torrent_file} downloaded successfully!".green
  end
rescue Interrupt, EOFError
  cli.say 'Interrupted!'.red
rescue SocketError
  cli.say "Couldn't perform action. Are you online?".red
end
